### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Dung-Han-Lee** [MarkusEich/cpf_segmentation#6]
Hello, I am new to Linux, and I am currently working on a unbuntu16.04 system, with PCL 1.8, openni, openCV 3.1.0 installed. I have encounter some issues  during "make", I got the following error messages:

/home/michael/cpf_segmentation/src/segmentation_kinect_test.cpp: In function ‘int main(int, char**)’:
/home/michael/cpf_segmentation/src/segmentation_kinect_test.cpp:85:3: error: ‘OpenNIGrabber’ is not a member of ‘pcl’
   pcl::OpenNIGrabber grabber;
   ^
/home/michael/cpf_segmentation/src/segmentation_kinect_test.cpp:86:3: error: ‘Grabber’ is not a member of ‘pcl’
   pcl::Grabber* interface = grabber;
   ^
/home/michael/cpf_segmentation/src/segmentation_kinect_test.cpp:86:17: error: ‘interface’ was not declared in this scope
   pcl::Grabber* interface = grabber;
                 ^
/home/michael/cpf_segmentation/src/segmentation_kinect_test.cpp:86:29: error: ‘grabber’ was not declared in this scope
   pcl::Grabber* interface = grabber;
                             ^
I checked the header files of grabber.h, it was pointing to the right folder. I really have no idea what's the problem here.

**Comment by trungtpham** [comment]
Hi Micheal,

I have removed the segmentation_kinect_test.cpp file which causes the error, and this file is not really useful. Please check out the latest version. Hope this will work.

Cheers,
Trung

**Comment by Dung-Han-Lee** [comment]
The file was successfully built! We will look further into employing for our application. Thank you very much!
